// Generated by CoffeeScript 1.6.2
(function() {
  var CSSDisplay;

  CSSDisplay = {
    resetBoard: function(marker) {
      var cell, col, row, str, _i, _j;
      str = "";
      for (row = _i = 0; _i <= 2; row = ++_i) {
        str += "<div id=\"row" + row + "\">";
        for (col = _j = 0; _j <= 2; col = ++_j) {
          cell = (3 * row) + col;
          str += "<div id=\"cell" + cell + "\">                  <button type=\"button\" class=\"button\">" + cell + "</button>                </div>";
        }
        str += "</div>";
      }
      return $("#board").html(str);
    },
    displayForm: function() {
      var str;
      str = "<div id=\"newGameForm\">            <div>              Marker:                <input type=\"radio\" name=\"marker\" value=\"X\" checked> X                <input type=\"radio\" name=\"marker\"   value=\"O\"> O            </div>            <div>              Move:                <input type=\"radio\" name=\"move\" value=\"0\" checked> First                <input type=\"radio\" name=\"move\" value=\"1\"> Second            </div>            <button type=\"button\" id=\"newGameButton\">Play!</button>          </div>";
      $("#board").append(str);
      return $("#newGameButton");
    },
    getCell: function(cellNum) {
      return $("#cell" + cellNum);
    },
    getButton: function(cellNum) {
      return $("#cell" + cellNum + " .button");
    },
    getMarker: function() {
      return $("input[name='marker']:checked").val();
    },
    getMove: function() {
      return $("input[name='move']:checked").val();
    },
    displayWinMessage: function() {
      return $("#board").prepend("<h1>You Win!</h1>");
    },
    displayLoseMessage: function() {
      return $("#board").prepend("<h1>You Lose!</h1>");
    },
    displayTieMessage: function() {
      return $("#board").prepend("<h1>It is a Tie!</h1>");
    }
  };

  (typeof exports !== "undefined" && exports !== null ? exports : this).CSSDisplay = CSSDisplay;

}).call(this);
