// Generated by CoffeeScript 1.6.2
(function() {
  var CSSDisplay, TicTacToe;

  CSSDisplay = {
    resetBoard: function(marker) {
      var cell, col, row, str, _i, _j;
      str = "";
      for (row = _i = 0; _i <= 2; row = ++_i) {
        str += "<div id=\"row" + row + "\">";
        for (col = _j = 0; _j <= 2; col = ++_j) {
          cell = (3 * row) + col;
          str += "<div id=\"cell" + cell + "\">                  <button type=\"button\" class=\"button\">" + cell + "</button>                </div>";
        }
        str += "</div>";
      }
      return $("#board").html(str);
    },
    displayForm: function() {
      var str;
      str = "<div id=\"newGameForm\">            <div>              Marker:                <input type=\"radio\" name=\"marker\" value=\"X\" checked> X                <input type=\"radio\" name=\"marker\"   value=\"O\"> O            </div>            <div>              Move:                <input type=\"radio\" name=\"move\" value=\"0\" checked> First                <input type=\"radio\" name=\"move\" value=\"1\"> Second            </div>            <button type=\"button\" id=\"newGameButton\">Play!</button>          </div>";
      $("#board").append(str);
      return $("#newGameButton");
    },
    getCell: function(cellNum) {
      return $("#cell" + cellNum);
    },
    getButton: function(cellNum) {
      return $("#cell" + cellNum + " .button");
    },
    getMarker: function() {
      return $("input[name='marker']:checked").val();
    },
    getMove: function() {
      return $("input[name='move']:checked").val();
    },
    displayWinMessage: function() {
      return $("#board").prepend("<h1>You Win!</h1>");
    },
    displayLoseMessage: function() {
      return $("#board").prepend("<h1>You Lose!</h1>");
    },
    displayTieMessage: function() {
      return $("#board").prepend("<h1>It is a Tie!</h1>");
    }
  };

  TicTacToe = {
    display: CSSDisplay,
    buttonsEnabled: false,
    boardState: "_________",
    resetBoard: function(marker) {
      var cell, _i, _results;
      TicTacToe.buttonsEnabled = false;
      TicTacToe.boardState = "_________";
      TicTacToe.display.resetBoard(marker);
      _results = [];
      for (cell = _i = 0; _i <= 8; cell = ++_i) {
        _results.push((function(cell) {
          return TicTacToe.display.getButton(cell).click(function() {
            if (TicTacToe.buttonsEnabled) {
              return TicTacToe.makeMove(marker, TicTacToe.boardState, cell);
            }
          });
        })(cell));
      }
      return _results;
    },
    displayForm: function() {
      var button;
      button = TicTacToe.display.displayForm();
      return button.click(function() {
        return TicTacToe.initializeGame();
      });
    },
    disableButtons: function() {
      return TicTacToe.buttonsEnabled = false;
    },
    enableButtons: function() {
      return TicTacToe.buttonsEnabled = true;
    },
    getNewBoardState: function(marker, boardState, cellNum) {
      return "" + (boardState.slice(0, cellNum)) + marker + (boardState.slice(cellNum + 1));
    },
    setUpBoard: function(marker) {
      return TicTacToe.resetBoard(marker);
    },
    updateBoardHuman: function(marker, boardState, move) {
      TicTacToe.disableButtons();
      TicTacToe.display.getCell(move).html(marker);
      return TicTacToe.boardState = boardState;
    },
    updateBoardAI: function(aiMarker, boardState, aiMove, result) {
      TicTacToe.display.getCell(aiMove).html(aiMarker);
      TicTacToe.boardState = boardState;
      switch (result) {
        case "W":
          TicTacToe.display.displayWinMessage();
          return TicTacToe.displayForm();
        case "L":
          TicTacToe.display.displayLoseMessage();
          return TicTacToe.displayForm();
        case "T":
          TicTacToe.display.displayTieMessage();
          return TicTacToe.displayForm();
        default:
          return TicTacToe.enableButtons();
      }
    },
    makeMove: function(marker, boardState, cellNum) {
      var aiMarker, newBoardState;
      newBoardState = TicTacToe.getNewBoardState(marker, boardState, cellNum);
      TicTacToe.updateBoardHuman(marker, newBoardState, cellNum);
      aiMarker = marker === "X" ? "O" : "X";
      return $.ajax({
        data: {
          marker: marker,
          board_state: newBoardState
        },
        dataType: "json",
        async: true,
        type: "POST",
        url: "/game",
        success: function(json) {
          return TicTacToe.updateBoardAI(aiMarker, json.boardState, json.aiMove, json.result);
        }
      });
    },
    initializeGame: function() {
      var aiMarker, marker, move;
      marker = TicTacToe.display.getMarker();
      move = TicTacToe.display.getMove();
      TicTacToe.setUpBoard(marker);
      aiMarker = marker === "X" ? "O" : "X";
      return $.ajax({
        data: {
          marker: marker,
          move: move
        },
        dataType: "json",
        async: true,
        type: "POST",
        url: "/",
        success: function(json) {
          return TicTacToe.updateBoardAI(aiMarker, json.boardState, json.aiMove, json.result);
        }
      });
    }
  };

  (typeof exports !== "undefined" && exports !== null ? exports : this).CSSDisplay = CSSDisplay;

  (typeof exports !== "undefined" && exports !== null ? exports : this).TicTacToe = TicTacToe;

  $(function() {
    return TicTacToe.displayForm();
  });

}).call(this);
